name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        # Avoid errors with .npmrc
        env:
          NPM_TOKEN: dummy

      - name: Run tests
        run: npm test